Basic_Capabilities:
  weight: 1.0
  children:
    Natural_Language_Understanding:
      weight: 1.0
      children:
        Elementary:
          weight: 0.3
          children:
            Text_Classification:
              weight: 1.0
              children:
                AGNews:
                  weight: 1.0
                THUCNews:
                  weight: 1.0
            Text_Matching:
              weight: 1.0
              children:
                LCQMC:
                  weight: 1.0
                QQP:
                  weight: 1.0
        Intermediate:
          weight: 0.55
          children:
            Reading_Comprehension_Extractive:
              weight: 1.0
              children:
                CMRC:
                  weight: 1.0
            Word_Sense_Disambiguation:
              weight: 1.0
              children:
                WiC:
                  weight: 1.0
        Advanced:
          weight: 0.15
          children:
            Reading_Comprehension:
              weight: 1.0
              children:
                C3:
                  weight: 1.0
                MultiRC:
                  weight: 1.0
                ReCoRD:
                  weight: 1.0
            Multi_Turn_Dialogue_Understanding:
              weight: 1.0
              children:
                UltraChat:
                  weight: 1.0
    Natural_Language_Inference:
      weight: 1.0
      children:
        Elementary:
          weight: 0.3
          children:
            Textual_Entailment:
              weight: 1.0
              children:
                OCNLI:
                  weight: 1.0
                MNLI:
                  weight: 1.0
                RTE:
                  weight: 1.0
        Intermediate:
          weight: 0.55
          children:
            Coreference_Resolution_and_Commonsense_Reasoning:
              weight: 1.0
              children:
                WSC:
                  weight: 1.0
            Multi_Turn_Dialogue_Reasoning:
              weight: 1.0
              children:
                MuTual:
                  weight: 1.0
        Advanced:
          weight: 0.15
          children:
            Causal_Reasoning:
              weight: 1.0
              children:
                COPA:
                  weight: 1.0
            First_Order_Logic_Reasoning:
              weight: 1.0
              children:
                FOLIO:
                  weight: 1.0
            Complex_Logic_Reasoning:
              weight: 1.0
              children:
                LogicNLI:
                  weight: 1.0
    Natural_Language_Generation:
      weight: 1.0
      children:
        Elementary:
          weight: 0.6
          children:
            Summarization:
              weight: 1.0
              children:
                LCSTS:
                  weight: 1.0
                CNewSum:
                  weight: 1.0
                VCSUM:
                  weight: 1.0
        Advanced:
          weight: 0.4
          children:
            Constrained_Text_Writing:
              weight: 1.0
              children:
                MulDimIF:
                  weight: 1.0
                Writing_Ability:
                  weight: 1.0
    Commonsense_Knowledge:
      weight: 1.0
      children:
        Elementary:
          weight: 0.3
          children:
            Everyday_Scenario_Commonsense:
              weight: 1.0
              children:
                HellaSwag:
                  weight: 1.0
            Commonsense_QA:
              weight: 1.0
              children:
                Cosmos:
                  weight: 1.0
            Physical_Commonsense:
              weight: 1.0
              children:
                PIQA:
                  weight: 1.0
        Intermediate:
          weight: 0.55
          children:
            Human_Cognition_and_Exam_Ability:
              weight: 1.0
              children:
                AGIEval:
                  weight: 1.0
            Multi_Task_Knowledge_Breadth:
              weight: 1.0
              children:
                CMMLU:
                  weight: 1.0
                MMLU-pro:
                  weight: 1.0
                CEval:
                  weight: 1.0
        Advanced:
          weight: 0.15
          children:
            Truthfulness_QA:
              weight: 1.0
              children:
                TruthfulQA:
                  weight: 1.0
Emotional_Intelligence:
  weight: 1.0
  children:
    Emotion_Recognition:
      weight: 1.0
      children:
        Elementary:
          weight: 0.3
          children:
            Sentiment_Polarity_Recognition:
              weight: 1.0
              children:
                IMDb:
                  weight: 1.0
                SST-2:
                  weight: 1.0
                Dianping:
                  weight: 1.0
        Intermediate:
          weight: 0.55
          children:
            Fine_Grained_Emotion_Recognition:
              weight: 1.0
              children:
                GoEmotions:
                  weight: 1.0
                CPED:
                  weight: 1.0
                EDOS:
                  weight: 1.0
                PQEmotion1:
                  weight: 1.0
            Irony_Detection:
              weight: 1.0
              children:
                SemEval-2018_Task_3:
                  weight: 1.0
            Metaphor_Detection:
              weight: 1.0
              children:
                VUA20:
                  weight: 1.0
        Advanced:
          weight: 0.15
          children:
            Complex_Emotion_Recognition:
              weight: 1.0
              children:
                EmoBenchB:
                  weight: 1.0
    Emotion_Understanding:
      weight: 1.0
      children:
        Elementary:
          weight: 0.4
          children:
            Emotion_Intensity_Understanding:
              weight: 1.0
              children:
                SemEval-2018_Task_1:
                  weight: 1.0
        Intermediate:
          weight: 0.6
          children:
            Emotion_Cause_Analysis:
              weight: 1.0
              children:
                PQEmotion2:
                  weight: 1.0
                EmoBenchC:
                  weight: 1.0
    Emotion_Management:
      weight: 1.0
      children:
        Intermediate:
          weight: 1.0
          children:
            Emotion_Strategy_Selection:
              weight: 1.0
              children:
                PQEmotion3:
                  weight: 1.0
    Emotional_Response:
      weight: 1.0
      children:
        Intermediate:
          weight: 0.7
          children:
            Empathetic_Expression:
              weight: 1.0
              children:
                ESConv:
                  weight: 1.0
                EmoBenchA:
                  weight: 1.0
                PQEmotion4:
                  weight: 1.0
        Advanced:
          weight: 0.3
          children:
            Context_Specific_Emotional_Response:
              weight: 1.0
              children:
                PQEmotion5:
                  weight: 1.0
            Personalized_Emotional_Response:
              weight: 1.0
              children:
                CPED:
                  weight: 1.0
    Comprehensive_Emotional_Intelligence:
      weight: 1.0
      children:
        Elementary:
          weight: 0.3
          children:
            Effective_Communication_Test:
              weight: 1.0
              children:
                liangbiao2:
                  weight: 1.0
        Intermediate:
          weight: 0.55
          children:
            Interpersonal_Relationship_Test:
              weight: 1.0
              children:
                liangbiao1:
                  weight: 1.0
        Advanced:
          weight: 0.15
          children:
            Emotional_Quotient_Test:
              weight: 1.0
              children:
                liangbiao8:
                  weight: 1.0
                liangbiao9:
                  weight: 1.0
Companionship_Ability:
  weight: 1.0
  children:
    Memory_Management:
      weight: 1.0
      children:
        Elementary:
          weight: 0.6
          children:
            Sequential_Order_Recall:
              weight: 1.0
              children:
                BookSort:
                  weight: 1.0
        Advanced:
          weight: 0.4
          children:
            Long_Term_Dialogue_Recall:
              weight: 1.0
              children:
                LongMemEval:
                  weight: 1.0
    Personalization_Ability:
      weight: 1.0
      children:
        Elementary:
          weight: 0.4
          children:
            Personalization_Degree:
              weight: 1.0
              children:
                PersonaFeedback:
                  weight: 1.0
        Intermediate:
          weight: 0.6
          children:
            Personalized_Emotional_Response:
              weight: 1.0
              children:
                CPED:
                  weight: 1.0
Values_and_Safety:
  weight: 1.0
  children:
    Values:
      weight: 1.0
      children:
        Elementary:
          weight: 0.4
          children:
            Bias_Detection:
              weight: 1.0
              children:
                CrowS-Pairs:
                  weight: 1.0
                StereoSet:
                  weight: 1.0
                BBQ:
                  weight: 1.0
                SafetyBench7:
                  weight: 1.0
        Intermediate:
          weight: 0.6
          children:
            Moral_Detection:
              weight: 1.0
              children:
                SafetyBench1:
                  weight: 1.0
    Safety:
      weight: 1.0
      children:
        Elementary:
          weight: 0.4
          children:
            Content_Safety:
              weight: 1.0
              children:
                SafetyBench3:
                  weight: 1.0
        Intermediate:
          weight: 0.6
          children:
            Information_Security:
              weight: 1.0
              children:
                SafetyBench4:
                  weight: 1.0
            User_Safety:
              weight: 1.0
              children:
                SafetyBench2:
                  weight: 1.0
                SafetyBench6:
                  weight: 1.0
            High_Risk_Harmful_Behavior:
              weight: 1.0
              children:
                SafetyBench5:
                  weight: 1.0
